### ISSUE TITLE
Readme.md Image Thread

### ISSUE THREAD

**Issue by FIN443** [boostcampaitech4lv23cv3/level2_dataannotation_cv-level2-cv-16#2]
![654c3b7b-c151-4f63-a378-cc102bbf773f](https://user-images.githubusercontent.com/70796031/214502172-c01ff25d-7814-407c-9f88-b4bd5acbcfdc.png)

**Comment by youngjun04** [comment]
![image](https://user-images.githubusercontent.com/113173095/214501669-b01738f5-91e4-4f00-9ed1-b0d394fda4bd.png)

**Comment by choipp** [comment]
![image](https://user-images.githubusercontent.com/103131249/214503241-f2105573-aaae-4c7f-a2a7-d5795ec883ba.png)

**Comment by youngjun04** [comment]
![image](https://user-images.githubusercontent.com/113173095/214503374-c40ecec0-d3e2-485e-b696-f384b723ffbd.png)

**Comment by FIN443** [comment]
![samples](https://user-images.githubusercontent.com/70796031/214503382-45ae15e0-7d98-4bf9-ac44-fb83b887b14e.png)

**Comment by youngjun04** [comment]
![image](https://user-images.githubusercontent.com/113173095/214503526-04a7e69e-fa9c-4bad-b0c0-293bae4475c4.png)

**Comment by FIN443** [comment]
<img width="1049" alt="스크린샷 2023-01-25 16 23 24" src="https://user-images.githubusercontent.com/70796031/214503731-6f7ba635-6390-4333-8295-e7040547490a.png">

**Comment by youngjun04** [comment]
![image](https://user-images.githubusercontent.com/113173095/214506080-f1608026-309e-4a09-a19d-755682b37549.png)

**Comment by youngjun04** [comment]
![image](https://user-images.githubusercontent.com/113173095/214508320-37f1e943-13d8-403c-9ba2-07a3a3b5bd7c.png)

**Comment by choipp** [comment]
![image](https://user-images.githubusercontent.com/103131249/214509631-cc8c0870-bbc8-46fa-8efb-9c252a76ced3.png)

**Comment by choipp** [comment]
![image](https://user-images.githubusercontent.com/103131249/214509779-3778e2a5-a66d-4fd4-a2d8-512630d0e8c9.png)

**Comment by choipp** [comment]
![image](https://user-images.githubusercontent.com/103131249/214510914-90e32259-e766-4537-9ab3-df3213d4ae36.png)

**Comment by choipp** [comment]
![image](https://user-images.githubusercontent.com/103131249/214511299-12b51c05-cf92-4f2c-a973-6c5f518eef69.png)

**Comment by choipp** [comment]
![image](https://user-images.githubusercontent.com/103131249/214511477-0b25d967-8cf3-46c3-b8d6-f9b2420b9c7e.png)

**Comment by choipp** [comment]
![image](https://user-images.githubusercontent.com/103131249/214511736-cebe9c5a-83b5-4f4a-898a-38f5da3b2129.png)

**Comment by choipp** [comment]
![image](https://user-images.githubusercontent.com/103131249/214512518-967a722e-cfac-401a-bb9a-8dc64922f5fa.png)

**Comment by choipp** [comment]
![image](https://user-images.githubusercontent.com/103131249/214512646-bd6acd0d-17e6-4884-9204-cce8585bcb71.png)

**Comment by choipp** [comment]
![image](https://user-images.githubusercontent.com/103131249/214513921-9c78bcdb-320c-4473-a8ce-73762b4491b7.png)

**Comment by choipp** [comment]
![image](https://user-images.githubusercontent.com/103131249/214514024-e8c98ae4-c446-4fa9-a343-e530369c6964.png)

**Comment by choipp** [comment]
![image](https://user-images.githubusercontent.com/103131249/214517208-7b4583a6-a678-4673-a933-0a9beaa2506b.png)
